stages:
  - test

code_style:
  stage: test
  image: gitlab-master.nvidia.com:5005/devtech-compute/gqe:latest_x86_64
  before_script:
    - source /conda/bin/activate gqe
  script:
    - pre-commit run --all-files --show-diff-on-failure
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

tests:
  stage: test
  image: gitlab-master.nvidia.com:5005/devtech-compute/gqe:latest_x86_64
  before_script:
    - source /conda/bin/activate gqe
  script:
    - hostname
    - nvidia-smi
    - export CCACHE_DIR=/ccache_files
    # For https links, the CI does not have access to the ssh keys, so we need to use deploy tokens.
    # Rather than have multiple deploy tokens for all dependencies, we use a single token for all dependencies, which is stored in the Variables section here: https://gitlab-master.nvidia.com/haog/gqe-python/-/settings/ci_cd.
    # TODO: Setup runner account for CI.
    - git config --global url."https://${GQE_NVCOMP_DEPLOY_USERNAME}:${GQE_NVCOMP_DEPLOY_TOKEN}@gitlab-master.nvidia.com/".insteadOf "https://gitlab-master.nvidia.com/"
    # The *_DEPLOY_* environment variables are set in Settings → CI/CD → Variables
    # They are created in the Deploy tokens sections of these links:
    #   https://gitlab-master.nvidia.com/Devtech-Compute/gqe-benchmarking/-/settings/repository
    #   https://gitlab-master.nvidia.com/Devtech-Compute/gqe/-/settings/repository
    - pip install -e .
    - conda install -y pytest
    # Run TPC-H parameter sweep.
    - gqe-run-parameter-sweep --json ./config_templates/tpch_sweep_CI.json5
    # Run all Python tests on TPC-H parameter sweep results.
    - pytest tests/ -v --database /tmp/gqe_experiment.db3
    # Run TPC-H pretuned with best parameters from sweep.
    - gqe-run-pretuned /tpch_scratch/datasets/sf0.01/sf0.01_id64 /tpch_scratch/substrait_plans/sf0.01 "/tpch_scratch/reference_results/sf0.01/%d.parquet" --swept-sqlite-file /tmp/gqe_experiment.db3 -o /tmp/gqe_pretuned.db3
    # Run only Python SQLite tests on TPC-H pretuned results.
    - pytest tests/test_sql_views.py -v --database /tmp/gqe_pretuned.db3
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
