stages:
  - test

code_style:
  stage: test
  image: gitlab-master.nvidia.com:5005/devtech-compute/gqe:latest_x86_64
  before_script:
    - source /conda/bin/activate gqe
  script:
    - pre-commit run --all-files --show-diff-on-failure
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

tests:
  stage: test
  image: gitlab-master.nvidia.com:5005/devtech-compute/gqe:latest_x86_64
  before_script:
    - source /conda/bin/activate gqe
  script:
    - hostname
    - nvidia-smi
    - export CCACHE_DIR=/ccache_files
    # For https links, the CI does not have access to the ssh keys, so we need to use deploy tokens.
    # Rather than have multiple deploy tokens for all dependencies, we use a single token for all dependencies, which is stored in the Variables section here: https://gitlab-master.nvidia.com/haog/gqe-python/-/settings/ci_cd.
    # Currently, the deploy token and username belongs to Yadu Kiran (ykiran)
    # TODO: Setup runner account for CI.
    - git config --global url."https://ykiran:glpat-5HRYzLFRBQWegJ8yPCiz@gitlab-master.nvidia.com/".insteadOf "https://gitlab-master.nvidia.com/"
    # The *_DEPLOY_* environment variables are set in the Variables sectionhere: https://gitlab-master.nvidia.com/haog/gqe-python/-/settings/ci_cd
    # They are created in the Deploy tokens sections of these links:
    #   https://gitlab-master.nvidia.com/Devtech-Compute/gqe-benchmarking/-/settings/repository
    #   https://gitlab-master.nvidia.com/Devtech-Compute/gqe/-/settings/repository
    - pip install -e .
    - conda install -y pytest
    - pytest tests/ -v
    - python ./gqe/benchmark/run_tpch_parameter_sweep.py --json ./gqe/tpch_sweep_config.template.json5
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
