# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved. SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: database_benchmarking_tools/diagrams/database_experiment_tables.svg
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.4
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]

  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: cmake-format -i
        language: python
        types: [cmake]
        additional_dependencies:
          - cmakelang==0.6.13
        require_serial: true

  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.4.0
    hooks:
      - id: verify-copyright
        exclude: cmake/CPM\.cmake$
