# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.4
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]

  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: cmake-format -i
        language: python
        types: [cmake]
        additional_dependencies:
          - cmakelang==0.6.13
        require_serial: true

  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.4.0
    hooks:
      - id: verify-copyright
        exclude: cmake/CPM\.cmake$
