# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved. SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# Write src/gqe_bench/_build_info.py describing the gqe checkout the engine
# binaries were built from. Run in script mode (cmake -P) by the _build_info_py
# target, which invokes it on every build so the recorded commit tracks the
# checkout.
#
# Required definitions:
#
# * GQE_DIR - gqe source directory to query
# * OUT - path of the Python module to write
#
# A directory that is not a git checkout, or a missing git executable, yields
# "unknown" revision/branch and a false dirty flag rather than a build failure.

find_package(Git QUIET)

set(_revision "unknown")
set(_branch "unknown")
set(_is_dirty "False")

if(Git_FOUND)
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse HEAD
    WORKING_DIRECTORY ${GQE_DIR}
    RESULT_VARIABLE _rev_result
    OUTPUT_VARIABLE _rev_output
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(_rev_result EQUAL 0)
    set(_revision "${_rev_output}")
  endif()

  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY ${GQE_DIR}
    RESULT_VARIABLE _branch_result
    OUTPUT_VARIABLE _branch_output
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(_branch_result EQUAL 0)
    set(_branch "${_branch_output}")
  endif()

  # Only meaningful once HEAD resolved; a non-checkout reports every path as
  # modified. Comparing against HEAD rather than the index counts staged changes
  # as dirty, matching what git describe --dirty reports.
  if(_rev_result EQUAL 0)
    execute_process(
      COMMAND ${GIT_EXECUTABLE} diff --quiet HEAD
      WORKING_DIRECTORY ${GQE_DIR}
      RESULT_VARIABLE _dirty_result
      ERROR_QUIET)
    if(NOT _dirty_result EQUAL 0)
      set(_is_dirty "True")
    endif()
  endif()
endif()

set(_content
    "# Auto-generated by CMake. Do not edit.
#
# Git state of the gqe checkout the engine binaries were built from, read at
# build time by cmake/build_info.cmake. Recorded into the experiment database's
# build_info table by gqe_bench.recording.

GIT_REVISION = \"${_revision}\"
GIT_BRANCH = \"${_branch}\"
GIT_IS_DIRTY = ${_is_dirty}
")

# Rewrite only on change so a no-op build does not restat the package as dirty.
if(EXISTS ${OUT})
  file(READ ${OUT} _existing)
  if(_existing STREQUAL _content)
    return()
  endif()
endif()
file(WRITE ${OUT} "${_content}")
