# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved. SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# Every generated file, and the values they are generated from. Included from
# the root CMakeLists.txt after the plugin subdirectory and the engine package,
# so the targets and variables referenced below exist.
#
# * nvtx_plugin/env.hpp - configure time, plugin on
# * nvtx_plugin/stages.hpp - configure time, plugin on
# * _artifacts.py - configure time, always
# * _build_info.py - build time when the engine is on, else a sentinel
# * _agg_protocol_sizes.py - build time when the plugin is on, else a sentinel
# * physical_plan/*_pb2.py - build time when the engine is on
#
# All of them are written under ${CMAKE_BINARY_DIR}/generated and none are
# edited by hand. The two headers are on the include path of the targets that
# compile the plugin sources; the Python modules reach the package through the
# install(FILES) rules at the bottom of this file. The sentinels exist because
# gqe_bench.recording imports from both _build_info and _agg_protocol_sizes
# unconditionally; they carry empty or zero values that the code paths guarded
# by Artifact.require() never reach. The protobuf modules need none:
# physical_plan/proto.py resolves them on attribute access, so an engine-off
# install still imports.

# Plugin-protocol constants: one definition feeding both languages, the C++
# plugin through env.hpp / stages.hpp and the Python layer through
# _artifacts.py. Because both are generated from these variables, the two views
# of the contract cannot drift. The authoritative per-constant documentation
# lives in the .in templates.
set(GQE_BENCH_DB_ENV "GQE_BENCH_DB")
set(GQE_BENCH_TIME_BREAKDOWN_ENV "GQE_BENCH_TIME_BREAKDOWN")
set(GQE_BENCH_CUPTI_METRICS_ENV "GQE_BENCH_CUPTI_METRICS")
set(GQE_BENCH_SHM_NAME_ENV "GQE_BENCH_SHM_NAME")
set(GQE_BENCH_NUM_RANKS_ENV "GQE_BENCH_NUM_RANKS")
set(GQE_BENCH_SHM_SIZE_ENV "GQE_BENCH_SHM_SIZE")
set(GQE_BENCH_LOG_LEVEL_ENV "GQE_BENCH_LOG_LEVEL")
set(STAGE_BUILD_METRIC "task_graph_generation")
set(STAGE_EXECUTE_METRIC "task_graph_execution")
set(STAGE_COLLECT_METRIC "output_generation")
set(TASK_MANAGER_PROGNAME "gqe_task_manager")

# env.hpp / stages.hpp: the constants above substituted into the plugin's
# templates, written to the build tree and put on the include path of every
# target that compiles the plugin sources. The size probe compiles
# agg_protocol.hpp, which includes stages.hpp, so it needs the path too.
if(GQE_BUILD_NVTX_PLUGIN)
  set(_generated_include_dir ${CMAKE_BINARY_DIR}/generated)
  configure_file(${PROJECT_SOURCE_DIR}/src/gqe_bench/nvtx_plugin/env.hpp.in
                 ${_generated_include_dir}/nvtx_plugin/env.hpp @ONLY)
  configure_file(${PROJECT_SOURCE_DIR}/src/gqe_bench/nvtx_plugin/stages.hpp.in
                 ${_generated_include_dir}/nvtx_plugin/stages.hpp @ONLY)
  target_include_directories(gqe_bench PRIVATE ${_generated_include_dir})
  target_include_directories(agg_protocol_size_probe
                             PRIVATE ${_generated_include_dir})
endif()

set(_generated_py_dir ${CMAKE_BINARY_DIR}/generated/gqe_bench)

# _artifacts.py: artifact metadata consumed by gqe_bench.resources. Filenames
# use $<TARGET_FILE_NAME> when the target exists and an empty string when its
# build flag is off; Artifact.locate() treats an empty filename as the "not
# built" sentinel.
if(GQE_BUILD_NVTX_PLUGIN)
  set(_PLUGIN_FILENAME_EXPR
      "gqe_bench/_artifacts/lib/$<TARGET_FILE_NAME:gqe_bench>")
else()
  set(_PLUGIN_FILENAME_EXPR "")
endif()
if(GQE_FETCH_ENGINE)
  set(_NODE_MANAGER_FILENAME_EXPR
      "gqe_bench/_artifacts/bin/$<TARGET_FILE_NAME:gqe_node_manager>")
  set(_TASK_MANAGER_FILENAME_EXPR
      "gqe_bench/_artifacts/bin/$<TARGET_FILE_NAME:gqe_task_manager>")
  set(_CLI_FILENAME_EXPR "gqe_bench/_artifacts/bin/gqe-cli")
else()
  set(_NODE_MANAGER_FILENAME_EXPR "")
  set(_TASK_MANAGER_FILENAME_EXPR "")
  set(_CLI_FILENAME_EXPR "")
endif()

file(
  GENERATE
  OUTPUT ${_generated_py_dir}/_artifacts.py
  CONTENT
    "# Auto-generated by CMake. Do not edit.
#
# Single source of truth for artifact metadata consumed by gqe_bench.resources.
# Env-var and stage-metric constants match those substituted into env.hpp and
# stages.hpp via configure_file in cmake/codegen.cmake.

from gqe_bench.resources import Artifact

PLUGIN = Artifact(
    name=\"plugin\",
    filename=\"${_PLUGIN_FILENAME_EXPR}\",
    build_flag=\"GQE_BUILD_NVTX_PLUGIN\",
    override_hint=\"\",
)
NODE_MANAGER = Artifact(
    name=\"node_manager\",
    filename=\"${_NODE_MANAGER_FILENAME_EXPR}\",
    build_flag=\"GQE_FETCH_ENGINE\",
    override_hint=\"--server-bin\",
    executable=True,
)
TASK_MANAGER = Artifact(
    name=\"task_manager\",
    filename=\"${_TASK_MANAGER_FILENAME_EXPR}\",
    build_flag=\"GQE_FETCH_ENGINE\",
    override_hint=\"--task-manager-bin\",
    executable=True,
)
CLI = Artifact(
    name=\"cli\",
    filename=\"${_CLI_FILENAME_EXPR}\",
    build_flag=\"GQE_FETCH_ENGINE\",
    override_hint=\"--cli-bin\",
    executable=True,
)
ALL = (PLUGIN, NODE_MANAGER, TASK_MANAGER, CLI)

GQE_BENCH_DB_ENV             = \"${GQE_BENCH_DB_ENV}\"
GQE_BENCH_TIME_BREAKDOWN_ENV = \"${GQE_BENCH_TIME_BREAKDOWN_ENV}\"
GQE_BENCH_CUPTI_METRICS_ENV  = \"${GQE_BENCH_CUPTI_METRICS_ENV}\"
GQE_BENCH_SHM_NAME_ENV       = \"${GQE_BENCH_SHM_NAME_ENV}\"
GQE_BENCH_NUM_RANKS_ENV      = \"${GQE_BENCH_NUM_RANKS_ENV}\"
GQE_BENCH_SHM_SIZE_ENV       = \"${GQE_BENCH_SHM_SIZE_ENV}\"
GQE_BENCH_LOG_LEVEL_ENV      = \"${GQE_BENCH_LOG_LEVEL_ENV}\"
STAGE_BUILD_METRIC           = \"${STAGE_BUILD_METRIC}\"
STAGE_EXECUTE_METRIC         = \"${STAGE_EXECUTE_METRIC}\"
STAGE_COLLECT_METRIC         = \"${STAGE_COLLECT_METRIC}\"
TASK_MANAGER_PROGNAME        = \"${TASK_MANAGER_PROGNAME}\"
")

# _build_info.py: git state of the gqe checkout the engine binaries were built
# from, which recording.py writes to the experiment database's build_info table.
# GQE_SOURCE_DIR names a local tree; otherwise CPM checked one out at
# GQE_GIT_TAG and set libgqe_SOURCE_DIR.
#
# Regenerated on every build: advancing the checkout to a new commit touches
# only sources, which does not re-run configure.
if(GQE_FETCH_ENGINE)
  if(DEFINED GQE_SOURCE_DIR)
    set(_GQE_CHECKOUT_DIR ${GQE_SOURCE_DIR})
  else()
    set(_GQE_CHECKOUT_DIR ${libgqe_SOURCE_DIR})
  endif()
  add_custom_target(
    _build_info_py ALL
    COMMAND
      ${CMAKE_COMMAND} -DGQE_DIR=${_GQE_CHECKOUT_DIR}
      -DOUT=${_generated_py_dir}/_build_info.py -P
      ${PROJECT_SOURCE_DIR}/cmake/build_info.cmake
    COMMENT "Generate _build_info.py from the gqe checkout"
    VERBATIM)
else()
  file(
    GENERATE
    OUTPUT ${_generated_py_dir}/_build_info.py
    CONTENT
      "# Auto-generated by CMake. Do not edit.
#
# Sentinel values - the gqe engine is not built, so there is no checkout to
# describe. When GQE_FETCH_ENGINE is on, cmake/build_info.cmake overwrites this
# file with the revision, branch, and dirty state of the gqe source tree.

GIT_REVISION = \"\"
GIT_BRANCH = \"\"
GIT_IS_DIRTY = False
")
endif()

# _agg_protocol_sizes.py: segment sizes from sizeof() and offsetof() of the
# compiled agg_protocol.hpp types, so Python's shared-memory sizing matches the
# layout the compiler produced. Only a compiler knows these values, hence the
# probe executable built alongside the plugin.
#
# Regenerated on every build.
if(GQE_BUILD_NVTX_PLUGIN)
  add_custom_target(
    _agg_protocol_sizes_py ALL
    COMMAND agg_protocol_size_probe ${_generated_py_dir}/_agg_protocol_sizes.py
    DEPENDS agg_protocol_size_probe
    COMMENT "Generate _agg_protocol_sizes.py from compiled agg_protocol.hpp"
    VERBATIM)
  add_dependencies(gqe_bench _agg_protocol_sizes_py)
else()
  file(
    GENERATE
    OUTPUT ${_generated_py_dir}/_agg_protocol_sizes.py
    CONTENT
      "# Auto-generated by CMake. Do not edit.
#
# Sentinel values - the NVTX plugin is not built. When GQE_BUILD_NVTX_PLUGIN is
# on, agg_protocol_size_probe overwrites this file with real values from
# sizeof() / offsetof() of the compiled types in agg_protocol.hpp.

K_HEADER_BYTES = 0
K_SLOT_BYTES = 0
K_HEADER_REQUEST_OFFSET = 0
")
endif()

# physical_plan/*_pb2.py: the physical-plan import closure, compiled from the
# same gqe checkout the engine is built from so the wire format cannot disagree
# with the client reading it. Doing it here rather than at import time keeps
# grpc_tools out of every process that imports gqe_bench: its protoc extension
# statically links a libprotobuf that segfaults against the one pyarrow mapped.
#
# protoc derives each module's cross-file imports from the path it is given, so
# the sources are staged under the package path with their imports rewritten to
# match. Compiled flat they would emit `import data_type_pb2`, which needs that
# directory on sys.path.
if(GQE_FETCH_ENGINE)
  # GQE resolves Protobuf inside its own directory scope, so the imported target
  # is not visible here; find it unless the engine has already put it in scope.
  # Same situation as spdlog in the root CMakeLists.txt.
  if(NOT TARGET protobuf::protoc)
    find_package(Protobuf REQUIRED)
  endif()

  set(_proto_names data_type expression physical_plan result)
  set(_proto_pkg_path gqe_bench/physical_plan)
  set(_proto_stage_root ${CMAKE_BINARY_DIR}/generated/proto_stage)
  set(_proto_stage_dir ${_proto_stage_root}/${_proto_pkg_path})

  set(_staged_protos "")
  set(_staged_proto_args "")
  set(_generated_pb2 "")
  foreach(_name IN LISTS _proto_names)
    file(READ ${_GQE_CHECKOUT_DIR}/proto/${_name}.proto _proto_text)
    string(
      REGEX
      REPLACE "import[ \t]+\"([A-Za-z0-9_]+)\\.proto\";"
              "import \"${_proto_pkg_path}/\\1.proto\";" _proto_text
              "${_proto_text}")
    file(WRITE ${_proto_stage_dir}/${_name}.proto "${_proto_text}")

    list(APPEND _staged_protos ${_proto_stage_dir}/${_name}.proto)
    list(APPEND _staged_proto_args ${_proto_pkg_path}/${_name}.proto)
    list(APPEND _generated_pb2
         ${_generated_py_dir}/physical_plan/${_name}_pb2.py)
  endforeach()

  add_custom_command(
    OUTPUT ${_generated_pb2}
    COMMAND protobuf::protoc --proto_path=${_proto_stage_root}
            --python_out=${CMAKE_BINARY_DIR}/generated ${_staged_proto_args}
    DEPENDS ${_staged_protos} protobuf::protoc
    COMMENT "Compile physical-plan protos to Python modules"
    VERBATIM)

  add_custom_target(_physical_plan_pb2_py ALL DEPENDS ${_generated_pb2})

  install(FILES ${_generated_pb2} DESTINATION ../physical_plan)
endif()

# These rules are how the modules reach the package: directly for wheel
# installs, and through scikit-build-core's editable redirect, which resolves
# them from the install directory, for editable installs. The three below are
# always present, generated when their flag is on and sentinel-written when it
# is off, so their install is unconditional.
install(FILES ${_generated_py_dir}/_artifacts.py
              ${_generated_py_dir}/_agg_protocol_sizes.py
              ${_generated_py_dir}/_build_info.py DESTINATION ..)
